# Generated by Django 6.1.1 on 2026-09-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTableSlot',
        ),
    ]
