# Generated by Django 6.1.1 on 2026-09-21 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_delete_timetableslot'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.teachingassignment')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot')),
            ],
            options={
                'ordering': ['assignment__school_class__id', 'time_slot__day', 'time_slot__start_time'],
            },
        ),
    ]
